# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build for TCB hosting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: build
        run: yarn build
      - name: tcb login and push
        run: |
          yarn tcb login --apiKeyId ${{ secrets.API_KEY_ID }} --apiKey ${{ secrets.API_KEY_SECRET }}
          yarn tcb hosting deploy docs/.vuepress/dist css-notes -e ${{ secrets.TCB_ENV }}
